# Generated by Django 4.0 on 2021-12-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rank_alter_employee_options_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['title'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.rank', verbose_name='Должность'),
        ),
    ]
